from __future__ import absolute_import, division, print_function
import os
import hashlib
import zipfile
# from six.moves import urllib
import torch


def readlines(filename):
    """Read all the lines in a text file and return as a list
    """
    with open(filename, 'r') as f:
        lines = f.read().splitlines()
    return lines


def normalize_image(x):
    """Rescale image pixels to span range [0, 1]
    """
    ma = float(x.max().cpu().data)
    mi = float(x.min().cpu().data)
    d = ma - mi if ma != mi else 1e5
    return (x - mi) / d


def sec_to_hm(t):
    """Convert time in seconds to time in hours, minutes and seconds
    e.g. 10239 -> (2, 50, 39)
    """
    t = int(t)
    s = t % 60
    t //= 60
    m = t % 60
    t //= 60
    return t, m, s


def sec_to_hm_str(t):
    """Convert time in seconds to a nice string
    e.g. 10239 -> '02h50m39s'
    """
    h, m, s = sec_to_hm(t)
    return "{:02d}h{:02d}m{:02d}s".format(h, m, s)

def charbonnier_loss(gt_flow, pred_flow, mask):
    '''
    This function computes the charbonnier loss between the flow predicted by
    PWC and the flow recovered after masking.
    Args:
        gt_flow: Optical Flow between the two images (Generated with PWC)
        pred_flow: Optical Flow recovered after masking (Generated by recover net)
        masks: The masks used to mask gt_flow (Generated by generator net)
        cbn: The Charbonnier Factor. 0.5 for L1 loss and 1.0 for L2 loss.
    Returns:
        error_sum: Vector of shape [batch_size,], where each element is the loss
                   summed over all pixels for a member of the batch.
    '''
    epsilon = 0.001
    lp_loss = (gt_flow - pred_flow).pow(2) + epsilon ** 2  # [4, 2, 48, 104]
    lp_loss = lp_loss.sqrt() # [4, 2, 48, 104]
    lp_loss = lp_loss*mask # [4, 2, 48, 104]
    return torch.sum(lp_loss, dim=[1,2,3])  # [B,] [4]

